### ISSUE TITLE
Upgrading Tesla

### ISSUE THREAD

**Issue by yordis** [edgurgel/httparrot#38]
As requested @edgurgel 

I am having some difficulty upgrading Tesla to OTP 26 and the httparrot SSL config, check the CI status: https://github.com/elixir-tesla/tesla/pull/623

I also tried to use OTP 25+ built-in public key certs stuff, but it didn't work, I am pretty sure something in the configuration is broken that I am failing to see.

I would appreciate some help with it.

**Comment by edgurgel** [comment]
Thanks, @yordis! Yeah we definitely need to update httparrot to run on newer Erlang and Elixir versions. Might need to review the SSL setup 🤔

**Comment by yordis** [comment]
It seems to be an SSL problem for sure, maybe the built-in certs needs to be updated or much better, using the OTP 25+ built-in functions to get the certs

**Comment by nathany-copia** [comment]
@edgurgel Any plans to update httparrot for Elixir 1.16?

I'm not sure how helpful I can be with certificate issues. 🤔 

Also related, would you like the Travis CI config updated for newer versions of Elixir and/or switch to GitHub Actions?

**Comment by edgurgel** [comment]
I'm going to sort out this SSL issue this weekend! The help with the GitHub Actions will great thank you

**Comment by nathany-copia** [comment]
Thanks @edgurgel.

**Comment by nathany-copia** [comment]
This issue can be closed.

https://github.com/elixir-tesla/tesla/pull/687 upgrades Tesla to httparrot 1.4, and all tests pass in Elixir 1.16. 

Thanks again @edgurgel.

**Comment by yordis** [comment]
@edgurgel, for my sanity's sake, ideally, we should document how to generate those SSLs somewhere, at the very least some `Make` command, even though we may not have the private key.

Regardless, thank you so much for the help! I gain a few white hairs over SSL (classic)

**Comment by edgurgel** [comment]
Oh I just used https://github.com/FiloSottile/mkcert ! I intend to later on make it so that it can generate on boot so it never expires as `mkcert`'s certificates expire after 2 years I think? :thinking:
